[package]
name = "me3-launcher"
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
description = "Launcher for me3"

[features]
sentry = ["me3_telemetry/sentry", "dep:sentry"]
default = []

[dependencies]
stable-eyre = { version = "0.2" }
crash-context.workspace = true
eyre = "0.6"
dll-syringe.workspace = true
ipc-channel.workspace = true
me3-launcher-attach-protocol.workspace = true
me3-mod-protocol.workspace = true
minidump-writer = "0.10"
tracing.workspace = true
sentry = { version = "0.38.1", optional = true }
toml.workspace = true
libc = "0.2.172"
me3_telemetry = { path = "../telemetry" }
tracing-subscriber.workspace = true

[lints]
workspace = true
