[package]
name = "me3-mod-host-assets"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Override game assets with local versions"

[dependencies]
cxx-stl = { version = "3", features = ["msvc2012"] }
thiserror.workspace = true
me3-mod-protocol.workspace = true
tracing.workspace = true

[lints]
workspace = true
