[package]
name = "me3_telemetry"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
sentry = ["dep:sentry"]
default = ["sentry"]

[dependencies]

tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
regex = { version = "1.11.1", features = ["unicode-case"] }

[dependencies.sentry]
version = "0.38"
default-features = false
features = [
    "tracing",
    "backtrace",
    "contexts",
    "debug-images",
    "panic",
    "reqwest",
    "rustls",
]
optional = true
[lints]
workspace = true
